export const ProgramIndicatorTemplate = {
    "id": "<indicatorId>",
    "name": "<Short Name> - Competency - C",
    "shortName": "<Short Name> - C",
    "description": "_H2LocalAnalytics",
    "aggregationType": "COUNT",
    "expression": "V{enrollment_count}",
    "sharing": {
        "external": false,
        "users": {},
        "userGroups": {},
        "public": "rw------"
    },
    "filter": "A{ulU9KKgSLYe} == \"competent\"",
    "analyticsType": "ENROLLMENT",
    "program": { "id": "<programId>" },
    "analyticsPeriodBoundaries": [
        {
            "externalAccess": false,
            "analyticsPeriodBoundaryType": "AFTER_START_OF_REPORTING_PERIOD",
            "boundaryTarget": "ENROLLMENT_DATE",
            "sharing": {
                "external": false,
                "users": {},
                "userGroups": {}
            },
            "favorite": false
        },
        {
            "externalAccess": false,
            "analyticsPeriodBoundaryType": "BEFORE_END_OF_REPORTING_PERIOD",
            "boundaryTarget": "ENROLLMENT_DATE",
            "sharing": {
                "external": false,
                "users": {},
                "userGroups": {}
            },
            "favorite": false
        }
    ]
}

export const compLastSixMonthsByOUTable = {
    "id": "<compLastSixMOUId>",
    "name": "<Short Name> - Competency Classes - (Last 6 months by Org Units)",
    "code": "<programId>_Scripted1",
    "legend": { "hidden": false },
    "publicAccess": "rw------",
    "userOrganisationUnitChildren": false,
    "legendDisplayStyle": "FILL",
    "type": "PIVOT_TABLE",
    "hideEmptyColumns": false,
    "subscribed": false,
    "userOrganisationUnit": true,
    "rowSubTotals": false,
    "cumulativeValues": false,
    "showDimensionLabels": false,
    "sortOrder": 0,
    "fontSize": "NORMAL",
    "favorite": false,
    "topLimit": 0,
    "userOrganisationUnitGrandChildren": false,
    "percentStackedValues": false,
    "noSpaceBetweenColumns": false,
    "showHierarchy": false,
    "hideTitle": false,
    "colorSet": "DARK",
    "skipRounding": false,
    "showData": true,
    "numberType": "VALUE",
    "hideEmptyRows": false,
    "displayDensity": "NORMAL",
    "regressionType": "NONE",
    "completedOnly": false,
    "colTotals": false,
    "hideEmptyRowItems": "NONE",
    "aggregationType": "DEFAULT",
    "hideSubtitle": false,
    "hideLegend": false,
    "externalAccess": false,
    "legendDisplayStrategy": "FIXED",
    "colSubTotals": false,
    "rowTotals": false,
    "digitGroupSeparator": "SPACE",
    "regression": false,
    "reportingParams": {
        "parentOrganisationUnit": false,
        "reportingPeriod": false,
        "organisationUnit": false,
        "grandParentOrganisationUnit": false
    },
    "relativePeriods": {
        "thisYear": false,
        "quartersLastYear": false,
        "last30Days": false,
        "last52Weeks": false,
        "thisWeek": false,
        "last90Days": false,
        "last60Days": false,
        "lastMonth": false,
        "last14Days": false,
        "biMonthsThisYear": false,
        "monthsThisYear": false,
        "last2SixMonths": false,
        "yesterday": false,
        "thisQuarter": false,
        "last12Months": false,
        "last5FinancialYears": false,
        "thisSixMonth": false,
        "lastQuarter": false,
        "thisFinancialYear": false,
        "last4Weeks": false,
        "last3Months": false,
        "thisDay": false,
        "thisMonth": false,
        "last5Years": false,
        "last6BiMonths": false,
        "last4BiWeeks": false,
        "lastFinancialYear": false,
        "lastBiWeek": false,
        "weeksThisYear": false,
        "last6Months": true,
        "last3Days": false,
        "quartersThisYear": false,
        "monthsLastYear": false,
        "lastWeek": false,
        "last7Days": false,
        "last180Days": false,
        "thisBimonth": false,
        "lastBimonth": false,
        "lastSixMonth": false,
        "thisBiWeek": false,
        "lastYear": false,
        "last12Weeks": false,
        "last4Quarters": false
    },
    "filterDimensions": ["pe"],
    "columns": [
        { "id": "dx" }
    ],
    "rowDimensions": ["ou"],
    "series": [],
    "columnDimensions": ["dx"],
    "dataDimensionItems": [],
    "organisationUnits": [],
    "filters": [
        { "id": "pe" }
    ],
    "rows": [
        { "id": "ou" }
    ]
}

export const compLastSixMonthsPie = {
    "id": "<compLastSixMPieId>",
    "name": "<Short Name> - Competency Classes - (Last 6 months)",
    "code": "<programId>_Scripted2",
    "legend": { "hidden": false },
    "publicAccess": "rw------",
    "userOrganisationUnitChildren": false,
    "legendDisplayStyle": "FILL",
    "type": "PIE",
    "hideEmptyColumns": false,
    "subscribed": false,
    "userOrganisationUnit": true,
    "rowSubTotals": false,
    "cumulativeValues": false,
    "showDimensionLabels": false,
    "sortOrder": 0,
    "fontSize": "NORMAL",
    "favorite": false,
    "topLimit": 0,
    "userOrganisationUnitGrandChildren": false,
    "percentStackedValues": false,
    "noSpaceBetweenColumns": false,
    "showHierarchy": false,
    "hideTitle": false,
    "colorSet": "DEFAULT",
    "skipRounding": false,
    "showData": true,
    "numberType": "VALUE",
    "hideEmptyRows": false,
    "displayDensity": "NORMAL",
    "regressionType": "NONE",
    "completedOnly": false,
    "colTotals": false,
    "hideEmptyRowItems": "NONE",
    "aggregationType": "DEFAULT",
    "hideSubtitle": false,
    "hideLegend": false,
    "externalAccess": false,
    "legendDisplayStrategy": "FIXED",
    "colSubTotals": false,
    "rowTotals": false,
    "digitGroupSeparator": "SPACE",
    "regression": false,
    "reportingParams": {
        "parentOrganisationUnit": false,
        "reportingPeriod": false,
        "organisationUnit": false,
        "grandParentOrganisationUnit": false
    },
    "relativePeriods": {
        "thisYear": false,
        "quartersLastYear": false,
        "last30Days": false,
        "last52Weeks": false,
        "thisWeek": false,
        "last90Days": false,
        "last60Days": false,
        "lastMonth": false,
        "last14Days": false,
        "biMonthsThisYear": false,
        "monthsThisYear": false,
        "last2SixMonths": false,
        "yesterday": false,
        "thisQuarter": false,
        "last12Months": false,
        "last5FinancialYears": false,
        "thisSixMonth": false,
        "lastQuarter": false,
        "thisFinancialYear": false,
        "last4Weeks": false,
        "last3Months": false,
        "thisDay": false,
        "thisMonth": false,
        "last5Years": false,
        "last6BiMonths": false,
        "last4BiWeeks": false,
        "lastFinancialYear": false,
        "lastBiWeek": false,
        "weeksThisYear": false,
        "last6Months": true,
        "last3Days": false,
        "quartersThisYear": false,
        "monthsLastYear": false,
        "lastWeek": false,
        "last7Days": false,
        "last180Days": false,
        "thisBimonth": false,
        "lastBimonth": false,
        "lastSixMonth": false,
        "thisBiWeek": false,
        "lastYear": false,
        "last12Weeks": false,
        "last4Quarters": false
    },
    "filterDimensions": [
        "pe",
        "ou"
    ],
    "columns": [
        { "id": "dx" }
    ],
    "rowDimensions": [],
    "series": [],
    "columnDimensions": ["dx"],
    "dataDimensionItems": [],
    "organisationUnits": [],
    "filters": [
        { "id": "pe" },
        { "id": "ou" }
    ]
}

export const compLastSixMonthsTable = {
    "id": "<compLastSixMId>",
    "name": "<Short Name> - Competency Classes - (Last 6 months)",
    "code": "<programId>_Scripted3",
    "legend": { "hidden": false },
    "publicAccess": "rw------",
    "userOrganisationUnitChildren": false,
    "legendDisplayStyle": "FILL",
    "type": "PIVOT_TABLE",
    "hideEmptyColumns": false,
    "subscribed": false,
    "userOrganisationUnit": true,
    "rowSubTotals": false,
    "cumulativeValues": false,
    "showDimensionLabels": false,
    "sortOrder": 0,
    "fontSize": "NORMAL",
    "favorite": false,
    "topLimit": 0,
    "userOrganisationUnitGrandChildren": false,
    "percentStackedValues": false,
    "noSpaceBetweenColumns": false,
    "showHierarchy": false,
    "hideTitle": false,
    "colorSet": "DARK",
    "skipRounding": false,
    "showData": true,
    "numberType": "VALUE",
    "hideEmptyRows": false,
    "displayDensity": "NORMAL",
    "regressionType": "NONE",
    "completedOnly": false,
    "colTotals": false,
    "hideEmptyRowItems": "NONE",
    "aggregationType": "DEFAULT",
    "hideSubtitle": false,
    "hideLegend": false,
    "externalAccess": false,
    "legendDisplayStrategy": "FIXED",
    "colSubTotals": false,
    "rowTotals": false,
    "digitGroupSeparator": "SPACE",
    "regression": false,
    "reportingParams": {
        "parentOrganisationUnit": false,
        "reportingPeriod": false,
        "organisationUnit": false,
        "grandParentOrganisationUnit": false
    },
    "relativePeriods": {
        "thisYear": false,
        "quartersLastYear": false,
        "last30Days": false,
        "last52Weeks": false,
        "thisWeek": false,
        "last90Days": false,
        "last60Days": false,
        "lastMonth": false,
        "last14Days": false,
        "biMonthsThisYear": false,
        "monthsThisYear": false,
        "last2SixMonths": false,
        "yesterday": false,
        "thisQuarter": false,
        "last12Months": false,
        "last5FinancialYears": false,
        "thisSixMonth": false,
        "lastQuarter": false,
        "thisFinancialYear": false,
        "last4Weeks": false,
        "last3Months": false,
        "thisDay": false,
        "thisMonth": false,
        "last5Years": false,
        "last6BiMonths": false,
        "last4BiWeeks": false,
        "lastFinancialYear": false,
        "lastBiWeek": false,
        "weeksThisYear": false,
        "last6Months": true,
        "last3Days": false,
        "quartersThisYear": false,
        "monthsLastYear": false,
        "lastWeek": false,
        "last7Days": false,
        "last180Days": false,
        "thisBimonth": false,
        "lastBimonth": false,
        "lastSixMonth": false,
        "thisBiWeek": false,
        "lastYear": false,
        "last12Weeks": false,
        "last4Quarters": false
    },
    "filterDimensions": ["ou"],
    "columns": [
        { "id": "pe" }
    ],
    "rowDimensions": ["dx"],
    "series": [],
    "columnDimensions": ["pe"],
    "dataDimensionItems": [],
    "organisationUnits": [],
    "filters": [
        { "id": "ou" }
    ],
    "rows": [
        { "id": "dx" }
    ]
}