import type { BaseIdentifiableObject } from './BaseIdentifiableObject';
import type { Category } from './Category';
import type { CategoryOptionGroupSet } from './CategoryOptionGroupSet';
import type { FileResource } from './FileResource';
import type { IsoDateString } from './IsoDateString';
import type { OrganisationUnit } from './OrganisationUnit';
import type { TwoFactorType } from './TwoFactorType';
import type { UserGroup } from './UserGroup';
import type { UserRole } from './UserRole';

export interface User extends BaseIdentifiableObject {
  uuid?: string;
  username?: string;
  externalAuth?: boolean;
  openId?: string;
  ldapId?: string;
  password?: string;
  secret?: string;
  twoFactorType?: TwoFactorType;
  passwordLastUpdated?: IsoDateString;
  userRoles?: UserRole[];
  cogsDimensionConstraints?: CategoryOptionGroupSet[];
  catDimensionConstraints?: Category[];
  previousPasswords?: string[];
  lastLogin?: IsoDateString;
  restoreToken?: string;
  idToken?: string;
  restoreExpiry?: IsoDateString;
  selfRegistered?: boolean;
  invitation?: boolean;
  disabled?: boolean;
  isCredentialsNonExpired?: boolean;
  isAccountNonLocked?: boolean;
  accountExpiry?: IsoDateString;
  surname?: string;
  firstName?: string;
  email?: string;
  phoneNumber?: string;
  jobTitle?: string;
  introduction?: string;
  gender?: string;
  birthday?: IsoDateString;
  nationality?: string;
  employer?: string;
  education?: string;
  interests?: string;
  languages?: string;
  welcomeMessage?: string;
  lastCheckedInterpretations?: IsoDateString;
  groups?: UserGroup[];
  whatsApp?: string;
  facebookMessenger?: string;
  skype?: string;
  telegram?: string;
  twitter?: string;
  avatar?: FileResource;
  organisationUnits?: OrganisationUnit[];
  dataViewOrganisationUnits?: OrganisationUnit[];
  teiSearchOrganisationUnits?: OrganisationUnit[];
  dataViewMaxOrganisationUnitLevel?: number;
  apps?: string[];
  settings?: Record<string, string>;
  verifiedEmail?: string;
  emailVerificationToken?: string;
}
